### ISSUE TITLE
Vertical piano layout

### ISSUE THREAD

**Issue by josephktcheung** [AudioKit/Keyboard#19]
### Description

I'd like to create a vertical piano layout similar to logic pro, which should be exactly the current `piano` layout but make it vertical.

Below is snapshot from logic pro. It's using traditional piano layout with raised black keys over white keys, while isomorphic layout places all notes linearly right after one another.

<img width="56" alt="Screenshot 2022-10-22 at 12 24 15 PM" src="https://user-images.githubusercontent.com/4270232/197318923-9fa0e3a7-a6b5-433d-80cb-e9a1e31d473f.png">

### Proposed Solution

Add a new `verticalPiano` layout which layout piano layout vertically.

### Describe Alternatives You've Considered

Fork the library and add the new layout

**Comment by aure** [comment]
Can you just take the regular piano and apply a rotation?

**Comment by josephktcheung** [comment]
> Can you just take the regular piano and apply a rotation?

<img width="481" alt="Screenshot 2022-10-22 at 12 45 24 PM" src="https://user-images.githubusercontent.com/4270232/197320222-c4a21a7c-0bf4-412f-a7dc-b85ee55414a2.png">
This is a snapshot after I rotate the piano by -90 degrees. It's okay but the words are vertically written which is a bit difficult to read.

Below is how I rotate it:

```swift
Keyboard(layout: .piano(pitchRange: (Pitch(36)...Pitch(75))))
    .rotationEffect(.degrees(-90))
```

**Comment by aure** [comment]
yeah, so constrain its width (or height pre-rotation) and you almost have it. I guess you want the labels to be rotated? I guess a .verticalPiano option is pretty trivial. Want to give it a shot?

**Comment by josephktcheung** [comment]
BTW I'm using the `verticalIsomorphic` layout in my project right now which already looks good to me, however there may be users who want to mimic logic pro / vocaloid editor to a T.
<img width="89" alt="Screenshot 2022-10-22 at 12 50 05 PM" src="https://user-images.githubusercontent.com/4270232/197320421-7d01f79b-73a3-4c59-befc-80790fdf1d86.png">

Also adding vertical piano layout is not difficult I believe.

**Comment by josephktcheung** [comment]
> yeah, so constrain its width (or height pre-rotation) and you almost have it. I guess you want the labels to be rotated? I guess a .verticalPiano option is pretty trivial. Want to give it a shot?

Sure, will open a PR sometime later.

**Comment by josephktcheung** [comment]
@aure please review https://github.com/AudioKit/Keyboard/pull/20
