### ISSUE TITLE
A way to pass MIDIMonitorData to keyboard to show what MIDI key is pressed

### ISSUE THREAD

**Issue by sidneivl** [AudioKit/Keyboard#23]
### Description

I'm not able to find out how show a Key pressed in MIDI keyboard to show on AudioKit Kayboard.

So if is possible to pass MIDIMonitorData directly to Keyboard in array pressed is easier way.

### Proposed Solution

Maybe with an state passing in array of MIDIMonitorData to show key pressed in MIDI Keyboard

### Describe Alternatives You've Considered

Could be a direct insert array of MIDIMonitorData after create.

**Comment by aure** [comment]
Demonstrated here https://github.com/AudioKit/Tonic/tree/main/Demo
