### ISSUE TITLE
Package resolution failed when Tonic 2.0 is installed

### ISSUE THREAD

**Issue by ksadowski** [AudioKit/Keyboard#30]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

**Environment:** macOS Sonoma 14.7.1, Xcode 16.2 (such versions are not available in picker BTW).

I'm setting up new project to try AudioKit using Tonic and Keyboard, but since Tonic was updated to 2.0 recently I see errors resolving the package.

**Steps to reproduce:**
1. Create new empty project - App
2. Add Packages: AudioKit, AudioKitEX, Tonic (latest versions)
3. Try to add Keyboard

**Result:**
I get package resolution failed message:

![Zrzut ekranu 2024-12-30 o 16 46 19](https://github.com/user-attachments/assets/45aa2fba-311a-4887-8a12-7de0aec7ea5f)

**Comment by aure** [comment]
Try Keyboard 1.4, seems to work for me.  Reset your package cache if you have to. let me know if you still have issues.

**Comment by ksadowski** [comment]
Yes it's fine with 1.4, thanks!
