### ISSUE TITLE
Remove Stuck Notes

### ISSUE THREAD

**Issue by NickCulbertson** [AudioKit/Keyboard#5]
There isn't currently a way to remove stuck notes. Also the keyboard appears to only handle 5 touches.

To reproduce: play and hold a note and swipe down from the top of the screen or the home indicator.

(I'll look into next week unless someone gets to it before me.)

**Comment by aure** [comment]
Reopened because there is still an issue when holding a lot of keys down (for me like 8 or 9 on an iPad Pro M1) and then swiping down.

**Comment by aure** [comment]
I can't get it to stick on 1.0.4

**Comment by NickCulbertson** [comment]
Yeah, it looks good!
