### ISSUE TITLE
5/7 = 12 violation

### ISSUE THREAD

**Issue by designerfuzzi** [AudioKit/Keyboard#8]
seems all fine, keyboard works. 
But!

Anytime i see some "keyboard" that places black and white keys as if they where bricks it might also sound like it. Why is that?

Because on touch devices sliding fingers results in pretty much constant ease or speed of incoming touch events with according timestamps. Triggering uneven spaced UI elements with fingers resulting in guaranteed predefined rhythmic musical rubbish!
In other words, such keyboard graphics influence the expression more than they actually improve it. Which leaves such keyboard layout as if they where only for testing pling pling dong dong, aha soundcard works. Not really pretty! 
Which in turn as everyone can see results in different keyboard styles that address one of each of those "problems" at once but never at all together.

The whole beauty of piano keys is their split in black (5 keys) and white (7 keys) with even spaced distance accross 12 different keys. That is also why building piano keyboards is some kind of art in itself for generations. 

Guessing that can be fixed but very likely has to be addressed deep in the graphics/UI code.

Some "weighted" properly spaced keys should be possible..

just saying. 

such code would have huge benefits apart from better (more natural) sounding rhythmic input when sliding fingers on it.
You could reduce the graphics code to one and the same algo that can change the "height" of the black keys to 100% of the height on white keys, also zooming them all together would guarantee simpler code instead of multiple algos all not really addressing musical spacing.

**Comment by aure** [comment]
I'm sorry but this is a rant rather than a helpful issue. Remove the hyperbole and explain what you want in as few as possible. Thanks.

**Comment by designerfuzzi** [comment]
12 keys spacing upper distance all the same.

No rant. writing because i did just that, but huu.. thanks for the brutal answer.
Ok then blunt straight out of my mouth.. shortest judgment: you see yet another collection of rectangles.
Thats not a keyboard!

**Comment by aure** [comment]
What app out there does it right in your opinion?. This is a young framework, anything is possible, just need to know what people  want.

**Comment by aure** [comment]
Does this look better to you? It was measure off a synth I have, this is built from a development branch.
![image](https://user-images.githubusercontent.com/13122/183530592-0a63e74b-dfbe-4be3-8082-747ff0aff3e3.png)
